services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: comissapro
      POSTGRES_PASSWORD: comissapro
      POSTGRES_DB: comissapro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
